### PR TITLE
Add github actions.

### PR DESCRIPTION
**Pull request by asherf**
because travis is no good anymore and adding GH actions will allow us to run tests on other OSs (windows, macos)
Keeping this side by side with travis for a while, but will eventually get rid of travis.

@mpdavis fyi

### CODE REVIEW

**Comment by asherf** [comment]
@mpdavis I think you need to enable GH actions for this repo when you have time.
thanks!

**Comment by mpdavis** [comment]
I believe actions are enabled, but I don't have any experience with setting them up. 

Screen Shot 2021-04-30 at 8 51 33 AM

Will changes to the actions trigger on the PR, or do they need to be merged first?

**Comment by asherf** [comment]
@mpdavis yes that did it. when u have time we need the branch protection rules updated to require the GH actions workflow to pass.

this is under: https://github.com/mpdavis/python-jose/settings/branches
looks like this:
Screen Shot 2021-04-30 at 7 45 17 AM

Screen Shot 2021-04-30 at 7 45 34 AM


Not urgent as I still have to updated the GH Actions workflow to handle code coverage.
thanks!

**Comment by mpdavis** [comment]
I set all of the GH actions as required. I can add code coverage when that is ready too.

**Pull request merged**
