### PR TITLE
Add more OS (windows, mac-os) support

### PR DESCRIPTION
**Pull request by asherf**
Underlying packages depend on native libraries so it is important to make sure things work across multiple operating systems. Github Actions makes it trivial.

### CODE REVIEW

**Comment by asherf** [comment]
@mpdavis merging this requires updating the branch protection rules.

https://github.com/mpdavis/python-jose/pull/233#issuecomment-830146674

This is also a good opportunity to remove the travis check from there(once that's done I'll remove the Travis config file)
I am planning to do a release (3.3.0) in the next week or so.

Thanks!

**Comment by asherf** [comment]
@mpdavis ping

**Comment by mpdavis** [comment]
@asherf Updated.

**Comment by asherf** [comment]
thanks!

**Pull request merged**
