### PR TITLE
Limit token size to 250 KB

### PR DESCRIPTION
**Pull request by princekhunt**

### CODE REVIEW

**Comment by smittysmee** [comment]
Bump on this

**Comment by smittysmee** [comment]
@princekhunt see above ☝️

**Comment by alistairwatts** [comment]
I've already opened a pull request for a more robust fix. See https://github.com/mpdavis/python-jose/pull/352

**Comment by twwildey** [comment]
This appears duplicative to https://github.com/mpdavis/python-jose/pull/352 - I will close this in favor of the other PR.

**Pull request closed without merging**
