### PR TITLE
add initial changelog with info for 3.1.0

### PR DESCRIPTION
**Pull request by mattsb42-aws**
As discussed in #129 and #99, this project currently lacks a changelog. I'm putting this here as a starting point for resolving that.

### CODE REVIEW

**Comment by zejn** [comment]
The changelog itself looks great, with one comment.

Looks to me that the Python "3.7" testing actually happens in Python 3.5. The testing environment itself is 3.7, but the tox command uses 3.5. See here https://travis-ci.org/mpdavis/python-jose/jobs/517511343#L237

**Comment by mattsb42-aws** [comment]
doh...that was a copy-paste fail on my part.

**Comment by mattsb42-aws** [comment]
#135 created to fix that

**Comment by zejn** [comment]
Thank you for this contribution, looks awesome now.

**Pull request merged**
