### PR TITLE
Fix deprecation warning from cryptography_backend.py

### PR DESCRIPTION
**Pull request by ibrag8998**
More info in #221

### CODE REVIEW

**Comment by cbetta** [comment]
👍🏻  to this, though I feel like this might break Jose with older versions of cryptography. Depending on when this change was introduced to cryptography (and the python versions python-jose wants to support) it might be wiser to try the one method and then fall back onto the other?

**Comment by danielknell** [comment]
int_from_bytes is a python 2.x compatibility method, which is thankfully now EoL.

int.from_bytes/to_bytes were added in python 3.2 about a decade ago.

**Comment by danielknell** [comment]
it's probably worth updating the calls to int_to_bytes also which will cause the same warning.

**Comment by chitopunk** [comment]
see #207

**Comment by cbetta** [comment]
Ah excellent, I had not seen that PR. 👍🏻

**Comment by MasterSergius** [comment]
Is there any info on when this PR is going to be merged?

**Comment by blag** [comment]
I won't have time for at least another month.

I highly recommend that at least one person on this thread ask @mpdavis to also become a maintainer.

**Comment by alanyee** [comment]
I am willing to become a maintainer so that some of the trivial, stale PRs/issues can be solved. How do I sign up?

**Comment by blag** [comment]
@alanyee 

> ask @mpdavis to also become a maintainer.

**Comment by asherf** [comment]
https://github.com/mpdavis/python-jose/pull/229 is now merged, I figured it would be faster than rebasing this PR so I cherry-picked the commit, PR'ed it and merged.
thanks for the fix!

**Pull request closed without merging**
