### PR TITLE
HMACKey.process_jwk

### PR DESCRIPTION
**Pull request by crgk**
Decided to take a crack at this, but I'm not sure if it's what you were looking for. I tried to follow the pattern set with `RSAKey.process_jwk`, but it seems strange to return the hmac instance. Feels to me like these should be classmethods to be used as factories for creating the `Key` objects.

Also started a test based on [the cookbook example](https://tools.ietf.org/html/draft-ietf-jose-cookbook-08#section-4.4), but did not commit it when it failed and became clear that I didn't know what I was doing.

### CODE REVIEW

**Comment by mpdavis** [comment]
JWks in general need gone over to use Keys instead of base RSA and HMAC instances everywhere.  This is a byproduct of not planning for JWKs to start out with and having to pull all of the key code into it's own module.

**Comment by mpdavis** [comment]
I would return the Key.  I think I messed up on the RSA one.

**Comment by crgk** [comment]
I'll try to turn this into a more comprehensive refractor, unless you want to handle changes at that scale yourself.

**Comment by mpdavis** [comment]
I think it is fairly straightforward, go for it. I can always just refuse
to merge the PR. :)

On Sun, Mar 6, 2016 at 9:56 AM Chad Knight <notifications@github.com> wrote:

> I'll try to turn this into a more comprehensive refractor, unless you want
> to handle changes at that scale yourself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mpdavis/python-jose/pull/16#issuecomment-192919830>.
>
-- 
Michael Davis

**Pull request closed without merging**
