### PR TITLE
Implement cryptography as one of the backends

### PR DESCRIPTION
**Pull request by zejn**
This pull request implements (optional) cryptography backend for both EC and RSA.

In order to be able to do that I had to refactor ``jose.jwk`` to make part of the jwk module importable by the backends. The utility functions ``base64_to_long`` and ``int_arr_to_long`` were moved to ``jose.utils`` and class ``Key`` was moved to ``jose.backends.base``.

In order to be able to support conversion and reuse between key implementations, each asymmetric key implementation (EC and RSA) now has two new methods. Method ``to_pem`` returns PEM encoded key data of six.binary_type. Method ``public_key`` returns public key from a private key or self when the instance represents public key.

Existing ECDSA signing implementation from ecdsa python library was moved into ``jose.backends.ecdsa_backend`` and existing PyCrypto was moved into ``jose.backends.pycrypto_backend``.

Default ``ECKey`` and ``RSAKey`` are chosen at import time in ``jose/backends/__init__.py``, but a better explicit selection might be useful. RSAKey defaults to pycrypto and fallbacks to cryptography backend and EC defaults to cryptography and fallbacks to ecdsa backend.

I've tested on Python 2.7 and Python 3.5.

### CODE REVIEW

**Comment by mpdavis** [comment]
First of all, thank you for putting this together.  At first glance this looks very good. 

I don't have time to dive into this tonight, but there are a couple of issues that look like they will be easy to fix.

1. The pypy tests are broken on Travis due to cryptography not supporting pypy < 2.6.  It looks like we can force a newer version of pypy. https://github.com/travis-ci/travis-ci/issues/4756

2. If I understand `jose/backends/__init__.py` correctly, this would require that PyCrypto or cryptography is installed, otherwise it will result in an ImportError.  If a user only needs to use HMAC signing (or EC using the ecdsa library).  We should handle instantiation without either library installed and throw an error at runtime if they try to sign/verify a token with a method that isn't supported.

Those are the only issues that came up from a quick pass through.

**Comment by zejn** [comment]
Very good observations, will try to fix. Thanks.

**Comment by zejn** [comment]
The RSAKey and ECKey in ``jose.jwk`` module are now imported from ``jose.backends`` and if import fails, nothing happens. This ensures the library isn't unusable if user only needs one of the implementations, which is available.

The Travis configuration file was updated to use tox-travis and now runs tests on newer version of PyPy and also CPython 3.5 and 3.6.

**Comment by mpdavis** [comment]
@zejn This looks great.  My apologies for taking so long to take a look.

**Comment by mpdavis** [comment]
Released in [1.4.0](https://github.com/mpdavis/python-jose/releases/tag/1.4.0)

**Pull request merged**
