### PR TITLE
Use pycryptodome, allowing the use of pycrypto on GAE

### PR DESCRIPTION
**Pull request by sirosen**
@mpdavis, is this method of GAE detection satisfactory?
I'm not an appengine user myself, so not ready to test, but I am interested in #43 getting merged.

Replaces / closes #43

### CODE REVIEW

**Comment by sirosen** [comment]
I can mock over the `google` module and explicitly test this, to make codecov happier, but it seems that this integration is very shouty about unimportant changes in coverage.

@mpdavis, maybe you want to set a `threshold` in `codecov.yaml`? The [doc](https://github.com/codecov/support/wiki/Codecov-Yaml) for that file says it can be set to a %. Anything that decreases coverage by <1%, for example, should not be marked as failure, IMO.

**Comment by sirosen** [comment]
I've just validated that this installs correctly on GAE.
Also, I think this closes #41 ?

**Comment by sirosen** [comment]
@mpdavis, a coworker just pointed out to me that `pycrypto` now fails to install on macOS 10.13
That elevates the importance of changing the default crypo lib off of `pycrypto`.

If this detection isn't satisfactory, I'm happy to swap it out for something else, but not being a GAE user it's hard to be confident in my testing.

**Comment by mpdavis** [comment]
That certainly would push us towards getting off of `pycrypto` as a default. 

I can look into testing this and getting it in. We will need some way to handle this.

**Comment by mpdavis** [comment]
https://github.com/mpdavis/python-jose/pull/57

**Pull request closed without merging**
